use serde::{Deserialize, Serialize};
use ts_rs::{Config, TS};

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
enum EventKind {
    RuntimeSnapshot,
    ProtocolMismatch,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
enum MetricSemantic {
    CpuUsage,
    ResidentMemory,
    ReadIoRate,
    NetworkRate,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
enum MetricScope {
    Process,
    Group,
    System,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
enum MetricUnit {
    PercentOneCore,
    Bytes,
    BytesPerSecond,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
struct MeasurementDescriptor {
    id: String,
    semantic: MetricSemantic,
    scope: MetricScope,
    unit: MetricUnit,
    interval_ms: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
enum MetricQuality {
    Native,
    Estimated,
    Held,
    Partial,
    Unavailable,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
struct MetricValue {
    descriptor_id: String,
    value: Option<f64>,
    quality: MetricQuality,
    observed_at_ms: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    limitation: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
struct ProcessDetail {
    stable_id: String,
    pid: String,
    display_name: String,
    metrics: Vec<MetricValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
struct GroupCoverage {
    included_processes: u32,
    total_processes: u32,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    limitations: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
struct GroupDetail {
    stable_id: String,
    display_name: String,
    coverage: GroupCoverage,
    metrics: Vec<MetricValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(tag = "kind", content = "detail", rename_all = "snake_case")]
enum WorkloadDetail {
    Process(ProcessDetail),
    Group(GroupDetail),
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
struct Compatibility {
    minimum_reader_version: u16,
    breaking: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    message: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
struct RuntimeEnvelope {
    protocol_version: u16,
    event_kind: EventKind,
    compatibility: Compatibility,
    descriptors: Vec<MeasurementDescriptor>,
    workloads: Vec<WorkloadDetail>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
struct ExistingOptionalWithoutDefault {
    required_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    optional_message: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
struct SkippedInternalField {
    visible_name: String,
    #[serde(skip)]
    #[allow(dead_code)]
    internal_only: String,
}

fn generated_typescript() -> String {
    let config = Config::default();
    let declarations = [
        EventKind::decl(&config),
        MetricSemantic::decl(&config),
        MetricScope::decl(&config),
        MetricUnit::decl(&config),
        MeasurementDescriptor::decl(&config),
        MetricQuality::decl(&config),
        MetricValue::decl(&config),
        ProcessDetail::decl(&config),
        GroupCoverage::decl(&config),
        GroupDetail::decl(&config),
        WorkloadDetail::decl(&config),
        Compatibility::decl(&config),
        RuntimeEnvelope::decl(&config),
        ExistingOptionalWithoutDefault::decl(&config),
        SkippedInternalField::decl(&config),
    ]
    .map(|declaration| declaration.replacen("type ", "export type ", 1));

    format!(
        "// Generated by the issue #66 ts-rs spike; do not edit by hand.\n\n{}\n",
        declarations.join("\n\n")
    )
}

#[test]
fn generated_typescript_matches_the_checked_fixture() {
    assert_eq!(
        generated_typescript(),
        include_str!("../../src/lib/generated/dto-spike.ts")
    );
}

#[test]
fn serde_optional_behavior_exposes_the_existing_generation_risk() {
    let existing = ExistingOptionalWithoutDefault {
        required_name: "current-pattern".to_string(),
        optional_message: None,
    };
    let clean = Compatibility {
        minimum_reader_version: 2,
        breaking: false,
        message: None,
    };

    assert_eq!(
        serde_json::to_value(existing).expect("serialize existing optional"),
        serde_json::json!({ "required_name": "current-pattern" })
    );
    assert_eq!(
        serde_json::to_value(clean).expect("serialize clean optional"),
        serde_json::json!({
            "minimum_reader_version": 2,
            "breaking": false
        })
    );
}
